site_name: Doc Utilisateur Lodel

pages:
- Introduction: 'index.md'

- UTILISATION:
  - 'Démarrer avec Lodel.md'
  - Découvrir l'interface de Lodel: 'Découvrir interface de Lodel.md'
  - 'Organiser la structure du site.md'
  - 'Configurer son site.md'
  - 'Importer un document.md'
  - Gérer les index et entrées d’index: 'Gérer index.md'

- CONFIGURER LODEL:
  - 'Configurer-Lodel/Principales notions.md'
  - 'Configurer-Lodel/Fonctionnalités.md'
  - 'Configurer-Lodel/Administrateur.md'
  - 'Configurer-Lodel/Editeur.md'

- 'Glossaire.md'
